# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdVRyGWwOi4V2hwf5d3nDODBu0b7DYoY
"""

import requests,json,time
BASE_URL="http://api.openweathermap.org/data/2.5/weather?"
CITY="Chennai"
API_Key="Your API Key"
URL=BASE_URL+"q="+CITY+"&appid"+API_KEY
response=requests.get(URL)
while(1):
  file=open("enter the path to the txt file" ,'w')
  if response.status_code==200:
    data=response.json()
    main=data['main']
    temperature=main['temp']
    humidity=main['humidity']
    f.write("Temparature:"temperature)
    f.write("Humidity:"humidity)
    f.close()
    time.sleep(10)
    else:
      print("Error in http")
      break